Switch from Firecracker to Cloud Hypervisor for testing ramfs

diff --git a/ramfs/test b/ramfs/test
--- a/ramfs/test
+++ b/ramfs/test
@@ -4,28 +4,16 @@ set -e -o pipefail
 shopt -s dotglob extglob globstar nullglob
 cd -- "${0%/*}"
 
-if ! type -t firecracker >/dev/null; then
-  echo 'Missing hypervisor: firecracker not found' 2>&1
+if ! type -t hyper >/dev/null; then
+  echo 'Missing hypervisor: hyper not found' 2>&1
   exit 1
-elif [[ ! -f ../../guest/boot/linux-amd64 ]]; then
-  echo 'Missing kernel: ../../guest/boot/linux-amd64 not found' 2>&1
+elif [[ ! -f ../../guest/boot/linux ]]; then
+  echo 'Missing kernel: ../../guest/boot/linux not found' 2>&1
   exit 1
 elif [[ ! -f ../boot/ramfs.cpio ]]; then
   echo 'Missing initramfs: ../boot/ramfs.cpio not found' 2>&1
   exit 1
 fi
 
-exec firecracker --config-file /dev/fd/3 --no-api 3<<EOF
-{
-  "boot-source": {
-    "kernel_image_path": "../../guest/boot/linux-amd64",
-    "initrd_path": "../boot/ramfs.cpio",
-    "boot_args": "quiet"
-  },
-  "machine-config": {
-    "vcpu_count": 1,
-    "mem_size_mib": 1024
-  },
-  "drives": []
-}
-EOF
+exec hyper --cpus boot=1 --memory size=1G --kernel=../../guest/boot/linux \
+  --initramfs=../boot/ramfs.cpio --cmdline quiet
